"""
Adaptive Behavior & Robustness Test Suite.
Verifies profanity handling, refusal recovery, question advancement, and live score telemetry.
"""

import sys
import os
import unittest
import json
import uuid

# Ensure backend root is on sys.path
backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from fastapi.testclient import TestClient
from app.main import app
from app.config import CANDIDATES_PATH


class TestAdaptiveBehaviorAndRobustness(unittest.TestCase):
    """Test suite for adaptive interviewing, profanity handling, and telemetry."""

    def setUp(self):
        self.client = TestClient(app)
        with open(CANDIDATES_PATH, "r", encoding="utf-8") as f:
            self.candidates = json.load(f)["candidates"]
        self.candidate = self.candidates[0]

    def test_profanity_and_refusal_advancement(self):
        """Verify that profanity or refusals do not loop or repeat questions."""
        session_id = f"test-robustness-{uuid.uuid4().hex[:6]}"

        # Turn 1: Initialization
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "candidate": self.candidate
        })
        self.assertEqual(res.status_code, 200)
        t1_reply = res.json()["reply"]

        # Turn 2: Abusive word
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "message": "fu*k off"
        })
        self.assertEqual(res.status_code, 200)
        t2_data = res.json()
        # Verify score is negative penalty (-25)
        self.assertEqual(t2_data.get("score"), -25)
        # Verify it did not repeat the exact same question
        self.assertNotEqual(t2_data["reply"], t1_reply)
        # Verify professional transition or warning
        self.assertTrue(
            "unprofessional" in t2_data["reply"].lower() or 
            "professional" in t2_data["reply"].lower()
        )

        # Turn 3: Refusal / gibberish
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "message": "qwerty"
        })
        self.assertEqual(res.status_code, 200)
        t3_data = res.json()
        self.assertIsNotNone(t3_data.get("score"))
        self.assertNotEqual(t3_data["reply"], t2_data["reply"])

        # Turn 4: "no" / refusal
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "message": "no"
        })
        self.assertEqual(res.status_code, 200)
        t4_data = res.json()
        self.assertNotEqual(t4_data["reply"], t3_data["reply"])

    def test_score_telemetry_in_responses(self):
        """Verify score and averageScore are returned on turns."""
        session_id = f"test-score-{uuid.uuid4().hex[:6]}"

        # Turn 1
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "candidate": self.candidate
        })
        self.assertEqual(res.status_code, 200)

        # Turn 2
        res = self.client.post("/api/interview", json={
            "sessionId": session_id,
            "message": "We compute cosine similarity on dense normalized vectors generated by text-embedding-004."
        })
        self.assertEqual(res.status_code, 200)
        data = res.json()
        self.assertIn("score", data)
        self.assertIn("averageScore", data)
        self.assertIn("coveredDays", data)
        self.assertIn("totalQuestions", data)
        self.assertGreater(data["score"], 40)


if __name__ == "__main__":
    unittest.main()
